import nodemailer from 'nodemailer';
let transporter=null;
function getTransporter(){if(transporter)return transporter;const{GMAIL_USER,GMAIL_APP_PASSWORD}=process.env;if(!GMAIL_USER||!GMAIL_APP_PASSWORD)return null;transporter=nodemailer.createTransport({service:'gmail',auth:{user:GMAIL_USER,pass:GMAIL_APP_PASSWORD}});return transporter}
export function emailConfigured(){return Boolean(process.env.GMAIL_USER&&process.env.GMAIL_APP_PASSWORD)}
export async function sendEmail({to,subject,html,text}){const t=getTransporter();if(!t||!to)return{sent:false,reason:'email-not-configured'};await t.sendMail({from:`DhenuSetu <${process.env.GMAIL_USER}>`,to,subject,html,text:text||undefined});return{sent:true}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function shell(title,label,color,content){return`<!doctype html><html><body style="margin:0;background:#f3f6f3;font-family:Arial,Helvetica,sans-serif;color:#203128"><div style="max-width:700px;margin:24px auto;background:#fff;border:1px solid #dde6df;border-radius:18px;overflow:hidden"><div style="background:#1f6844;color:#fff;padding:24px 28px"><div style="font-size:12px;letter-spacing:.14em;opacity:.82">DHENUSETU</div><h1 style="font-size:25px;margin:7px 0 0">${esc(title)}</h1></div><div style="padding:28px">${label?`<span style="display:inline-block;padding:7px 11px;border-radius:999px;background:${color}18;color:${color};font-weight:700;font-size:12px">${esc(label)}</span>`:''}${content}<div style="border-top:1px solid #e5ebe7;margin-top:26px;padding-top:16px;color:#7a857e;font-size:12px">This is an automated DhenuSetu notification related to your account or connected farm. Review the full record in the DhenuSetu application.</div></div></div></body></html>`}
function row(label,value){return`<tr><td style="padding:8px 10px;color:#718078">${esc(label)}</td><td style="padding:8px 10px;font-weight:700;text-align:right">${esc(value)}</td></tr>`}
export const templates={
 welcome:(name,role)=>({subject:`Welcome to DhenuSetu — ${role||'account'} created`,html:shell('Welcome to DhenuSetu','Account created','#2f7d4b',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p>Your <strong>${esc(role||'user')}</strong> account has been created successfully.</p><div style="background:#f6faf7;border:1px solid #e0e9e2;border-radius:14px;padding:16px"><strong>Start with DhenuSetu</strong><ul style="line-height:1.8"><li>Complete your profile and farm details.</li><li>Add each animal with its individual identity.</li><li>Record daily milk and health observations.</li><li>Monitor mastitis early-warning indicators.</li><li>Connect with your veterinarian.</li></ul></div><p>Firebase will separately send the official email-verification message configured for your project.</p><p>Regards,<br><strong>DhenuSetu Team</strong></p>`)}),
 risk:(name,animal,details={})=>({subject:`DhenuSetu alert — ${animal||'Animal'}: ${details.level||'attention required'} risk`,html:shell('Mastitis risk alert',`${details.level||'Risk'} · ${details.risk??'—'}%`,'#bd4c48',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p>The current screening information for <strong>${esc(animal||'Animal')}</strong> requires attention.</p><table width="100%" style="border-collapse:collapse;background:#fafcfb;border:1px solid #e2e9e4">${row('Animal ID / Tag',details.animalTag||'—')}${row('Farm',details.farm||'—')}${row('Risk level',details.level||'—')}${row('Risk score',details.risk!=null?`${details.risk}%`:'—')}</table><h3>Observed inputs</h3><table width="100%" style="border-collapse:collapse">${row('Body temperature',details.temp!=null?`${details.temp} °C`:'—')}${row('Milk yield',details.milk!=null?`${details.milk} L/day`:'—')}${row('SCC',details.scc!=null?`${details.scc} thousand cells/mL`:'—')}${row('Milk conductivity',details.conductivity??'—')}${row('Milk pH',details.pH??'—')}${row('Activity',details.activity??'—')}${row('Rumination',details.rumination??'—')}${row('Environment / hygiene',details.hygiene??'—')}</table><div style="margin-top:18px;padding:15px;background:#fff7f6;border-left:4px solid #bd4c48;border-radius:10px"><strong>Suggested action</strong><p>${esc(details.recommendation||'Review the animal and contact the connected veterinarian for appropriate guidance.')}</p></div><p style="font-size:12px;color:#78837c">This is an early-warning screening indicator, not a veterinary diagnosis.</p>`)}),
 connection:(name,other,body,details={})=>({subject:`DhenuSetu — connection update from ${other||'your connection'}`,html:shell('Connection update','Connection','#2f7d4b',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p>${esc(body||'Your connection status has changed.')}</p><table width="100%" style="border-collapse:collapse;background:#fafcfb;border:1px solid #e2e9e4">${row('Other profile',other||'—')}${row('Role',details.role||'—')}${row('Status',details.status||'—')}</table><p>Open the Connections section in DhenuSetu to review the current relationship.</p>`)}),
 connectionRequest:(name,requester,body,details={})=>({subject:`DhenuSetu — new connection request from ${requester||'a DhenuSetu user'}`,html:shell('New connection request','Action required','#4478c0',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p><strong>${esc(requester||'A DhenuSetu user')}</strong> has sent you a connection request on DhenuSetu.</p><table width="100%" style="border-collapse:collapse;background:#fafcfb;border:1px solid #e2e9e4">${row('Requester',requester||'—')}${row('Role',details.role||'—')}${row('Profile ID',details.profileId||'—')}${row('Farm / clinic',details.organization||'—')}</table><div style="margin-top:18px;padding:16px;background:#f5f8ff;border-left:4px solid #4478c0;border-radius:10px"><strong>What to do next</strong><p>Open the DhenuSetu app, go to <strong>Connection requests</strong>, and approve or reject this request.</p></div><p>${esc(body||'Review the request in the app when convenient.')}</p><p style="font-size:12px;color:#78837c">Please do not reply to this automated email.</p>`)}),
 lab:(name,animal,status,details={})=>({subject:`DhenuSetu — ${animal||'Animal'} lab report is ${status||'updated'}`,html:shell('Laboratory report update',status||'Updated','#4478c0',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p>The laboratory report for <strong>${esc(animal||'Animal')}</strong> has been updated.</p><table width="100%" style="border-collapse:collapse;background:#fafcfb;border:1px solid #e2e9e4">${row('Animal ID / Tag',details.animalTag||'—')}${row('Test name',details.testName||'—')}${row('Laboratory',details.labName||'—')}${row('Sample date',details.sampleDate||'—')}${row('Current status',status||'—')}${row('Farmer',details.farmerName||'—')}${row('Farm',details.farm||'—')}</table><div style="margin-top:16px;padding:15px;background:#f5f8ff;border-left:4px solid #4478c0;border-radius:10px"><strong>Observation / result</strong><p style="white-space:pre-wrap">${esc(details.result||'No observation text was included.')}</p></div>${details.closureComment?`<div style="margin-top:16px;padding:15px;background:#f6faf7;border-left:4px solid #2f7d4b;border-radius:10px"><strong>Doctor review / closure note</strong><p style="white-space:pre-wrap">${esc(details.closureComment)}</p></div>`:''}<p>Open DhenuSetu to view the complete report and live status.</p>`)}),
 message:(name,details={})=>({subject:`DhenuSetu — new message from ${details.from||'your connection'}`,html:shell('New message','Message','#2f7d4b',`<p style="font-size:16px">Hello ${esc(name||'there')},</p><p>You received a new message from <strong>${esc(details.from||'your connection')}</strong>.</p><table width="100%" style="border-collapse:collapse;background:#fafcfb;border:1px solid #e2e9e4">${row('Time',details.time||'Just now')}${row('Attachment',details.hasAttachment?'Yes':'No')}</table><div style="margin-top:16px;padding:16px;background:#f4f8f5;border-left:4px solid #2f7d4b;border-radius:10px"><strong>Message</strong><p style="white-space:pre-wrap">${esc(details.message||'No text message was included. There may be a photo attachment.')}</p></div><p>Open DhenuSetu to reply.</p>`)})
};
