import express from 'express';
import { getDb } from '../config/firebase.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { riskFromReading } from '../services/risk.js';
import { dispatchUserNotification } from '../services/notificationDispatcher.js';

const router=express.Router();
router.post('/pair',requireAuth,requireRole('Farmer'),async(req,res)=>{try{const {deviceId,animalId}=req.body||{};if(!deviceId||!animalId)return res.status(400).json({message:'deviceId and animalId are required.'});const normalized=String(deviceId).trim().toUpperCase();if(!/^[A-Z0-9:_-]{4,80}$/.test(normalized))return res.status(400).json({message:'Invalid ESP32 device ID.'});const db=getDb();const a=await db.collection('animals').doc(animalId).get();if(!a.exists||a.data().ownerId!==req.firebaseUser.uid)return res.status(404).json({message:'Animal not found.'});const existing=await db.collection('hardware').doc(normalized).get();if(existing.exists&&existing.data().ownerId!==req.firebaseUser.uid)return res.status(409).json({message:'This ESP32 is already paired to another farm.'});const now=new Date().toISOString();await db.collection('hardware').doc(normalized).set({deviceId:normalized,animalId,ownerId:req.firebaseUser.uid,pairedAt:now,updatedAt:now},{merge:true});await a.ref.set({hardware:{deviceId,pairedAt:now} ,updatedAt:now},{merge:true});res.json({ok:true,deviceId:normalized,animalId,pairedAt:now})}catch(e){res.status(500).json({message:e.message})}});
router.post('/unpair',requireAuth,requireRole('Farmer'),async(req,res)=>{try{const {deviceId,animalId}=req.body||{};const db=getDb();if(deviceId)await db.collection('hardware').doc(deviceId).delete();if(animalId)await db.collection('animals').doc(animalId).set({hardware:null,updatedAt:new Date().toISOString()},{merge:true});res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
router.post('/readings',async(req,res)=>{try{const token=req.headers['x-device-token'];if(!process.env.DEVICE_INGEST_TOKEN||token!==process.env.DEVICE_INGEST_TOKEN)return res.status(401).json({message:'Invalid device token.'});const {deviceId,timestamp,bodyTemperature,activity,rumination,milkTemperature,milkYield,scc,conductivity,pH}=req.body||{};if(!deviceId)return res.status(400).json({message:'deviceId is required.'});const normalized=String(deviceId).trim().toUpperCase();if(!/^[A-Z0-9:_-]{4,80}$/.test(normalized))return res.status(400).json({message:'Invalid deviceId.'});const db=getDb();const hw=await db.collection('hardware').doc(normalized).get();if(!hw.exists)return res.status(404).json({message:'Device is not paired.'});const h=hw.data();const risk=riskFromReading({temp:bodyTemperature,milk:milkYield,scc,conductivity,pH,activity,rumination});const readingRef=db.collection('sensorReadings').doc();const row={id:readingRef.id,deviceId:normalized,animalId:h.animalId,ownerId:h.ownerId,timestamp:timestamp||new Date().toISOString(),bodyTemperature,activity,rumination,milkTemperature,milkYield,scc,conductivity,pH,risk:risk.risk,level:risk.level};await readingRef.set(row);const animalRef=db.collection('animals').doc(h.animalId);const patch={updatedAt:new Date().toISOString(),deviceId:normalized,hardware:{...h,lastSeenAt:row.timestamp},latestSensorReadingId:readingRef.id};for(const[k,v] of Object.entries({temp:bodyTemperature,activity,rumination,milk:milkYield,scc,conductivity,pH})){if(v!==undefined&&v!==null)patch[k]=v;}if(risk.risk!==null){patch.risk=risk.risk;patch.level=risk.level;}await animalRef.set(patch,{merge:true});
if(risk.level==='High'||risk.level==='Moderate'){
  const animalSnap=await animalRef.get();const animal=animalSnap.data()||{};
  const title=`${risk.level} mastitis risk: ${animal.name||h.animalId}`;
  const body=`${animal.name||'Animal'} (${animal.tag||h.animalId}) has a ${risk.level.toLowerCase()} risk score of ${risk.risk}%. Review DhenuSetu now.`;
  await dispatchUserNotification({recipientId:h.ownerId,title,body,data:{type:'risk',animalId:h.animalId,risk:risk.risk,level:risk.level,details:{risk:risk.risk,level:risk.level,temp:bodyTemperature,scc,conductivity,pH,activity,rumination}},kind:'risk',emailTemplate:'risk',animalName:animal.name||h.animalId});
  const [c1,c2]=await Promise.all([db.collection('connections').where('fromId','==',h.ownerId).get(),db.collection('connections').where('toId','==',h.ownerId).get()]);
  const vetIds=[...c1.docs,...c2.docs].map(d=>d.data()).filter(c=>c.status==='approved').map(c=>c.fromId===h.ownerId?c.toId:c.fromId);
  for(const id of [...new Set(vetIds)]){const v=await db.collection('users').doc(id).get();if(v.exists&&v.data().role==='Vet')await dispatchUserNotification({recipientId:id,title,body,data:{type:'risk',animalId:h.animalId,risk:risk.risk,level:risk.level,details:{risk:risk.risk,level:risk.level,temp:bodyTemperature,scc,conductivity,pH,activity,rumination}},kind:'risk',emailTemplate:'risk',animalName:animal.name||h.animalId});}
}
res.status(201).json({ok:true,reading:row})}catch(e){res.status(500).json({message:e.message})}});
export default router;
